#!/bin/sh

BASEDIR=$(dirname "$0")

CMAKE_PATH={%CMAKEPATH%}
if [ ! -z "$CMAKE_PATH" ]
then
    "$CMAKE_PATH/cmake" -P "$BASEDIR/subgine-pkg.cmake" "$@"
else
    cmake -P "$BASEDIR/subgine-pkg.cmake" $@
fi
